### ISSUE TITLE
few minor issues

### ISSUE THREAD

**Issue by ppathak8** [scexao-org/scexaoWEB#1]
Hi Oli,

I tested the page, it needs the following file in the home directory "banner.png", "style.css"
"javascript.js", "script.js" and add these two lines after line 45 in "mkheader" to get the correct syntax for javascripts:

echo "  <script src=\"${RELPATH}javascript.js\" type=\"text/javascript\"></script>"
echo "  <script src=\"${RELPATH}script.js\" type=\"text/javascript\"></script>"

I guess, you still need to finish your C-code to produce correct navigation path for sub-folders. 

But overall this is amazing, I like the concept, will implement something similar in Python.

**Comment by oguyon** [comment]
I did the changes above
Thanks !

Note that we are not yet using the javascript features - some work needed to merge them back into the menu
